sunfish: Fetch vendor from personal repo
Forking vendor tree into Evolution X org repositories requires
privileged rights, and pushing fails due to git lfs:

batch request: git@lfs.undocumented.software: Permission denied (publickey).: exit status 255
error: failed to push some refs to 'github.com:Evolution-X-Devices/vendor_google_sunfish.git'

Fetching vendor tree from personal repo as a work-around.